### ISSUE TITLE
Step 5

### ISSUE THREAD

**Issue by swishswish123** [nicholsons/comp0034-wk1#1]
From the following sentence, 
"static contains CSS and JavaScript files. The files in the folders are downloaded from [Bootstrap](https://getbootstrap.com/)."

Folder `static` seems to be missing in flask_app2

**Comment by nicholsons** [comment]
Thank you. I hadn't added the Bootstrap css and js to tracking so it wasn't pushed, and empty directories don't appear on GitHub. Corrected now.
